Specify overflow property to avoid vertical and horizontal overflow in CardLayout
qbicsoftware/data-manager-app pull request #117
Opened 2022-10-06 15:19 UTC by Steffengreiner

**What was changed** 
Specifies the overflow property in the card-layout.css file to auto to avoid vertical and horizontal overflow. 

**Technical details**
The overflow css property specifies what should happen if a layout is too small to contain its content. 
It's default behaviour is set to visible(See [here](https://www.w3schools.com/csS/css_overflow.asp) for details), which leads to showing the content in the textfield outside of the cardlayout. 
Setting it to auto keeps the content within the window and makes a scrollbar appear if layout is too small for the content within.

2022-10-07 06:43 UTC, jenniferboedker reviewed
Very nice!

Question: can we add spacing so that if the window is resized the text has a fixed spacing in the card? I mean the spacing especially on the left and right border. Additionally it would be cool to have it on the top and bottom as well

<img width="505" alt="Screenshot 2022-10-07 at 08 28 37" src="https://user-images.githubusercontent.com/20778777/194484037-e8eee85c-1817-4b34-bd1f-e2b9bda2f82a.png">

2022-10-07 06:44 UTC, jenniferboedker requested changes
I would require the fixed spacing on the bottom and top since it appeared with this fix and would appreciate if we can tackle the same issue for the left and right side in this PR as well :)

2022-10-12 06:22 UTC, Steffengreiner commented
Heya @jenniferboedker, I added a small padding on the bottom of the formlayout which will lead to the scrollbar be triggered before the formlayout is reached. As we discussed maybe a complete overhaul of the layout structure within the cardlayout makes sense but would be outside of the scope of this PR

2022-10-12 07:32 UTC, jenniferboedker approved these changes

2022-10-12 08:12 UTC, merged