Provide first experimental design model
qbicsoftware/data-manager-app pull request #160
Opened 2023-01-17 13:49 UTC by sven1103

2023-01-18 14:48 UTC, KochTobi requested changes

2023-01-18 14:48 UTC, KochTobi commented on projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/ExperimentalVariable.java
> +    this.levels = Collections.unmodifiableList(Arrays.asList(levels));
This allows for a creation of an experimental variable without any levels. I think at least one? or two? is required.

2023-01-18 14:48 UTC, KochTobi commented on projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/ExperimentalDesign.java
> +  private boolean doesNotExist(String name) {
what does not exist? Maybe we can change the method name to `experimentalVariableDoesNotExist`

2023-01-18 14:48 UTC, KochTobi commented on projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/Condition.java
> +
I think at least one variable must be defined.

2023-01-18 14:48 UTC, KochTobi commented on projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/ExperimentalDesign.java
> +            "At least one experiment variable is not defined in the design.")));
This message might not match the error. If the condition checks for at least one variable and none is given here, this leads to a wrong error message.

2023-01-18 14:48 UTC, KochTobi commented on projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/ExperimentalDesign.java
> +    Optional<Condition> result = findCondition(conditionId);
maybe rename this variable to something else than result. maybe optionalCondition?

2023-01-18 14:48 UTC, KochTobi commented on projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/ExperimentalDesign.java
> +      return false;
You could flip the if statement here.
```suggestion
      if (!isVariablePartOfDesign(experimentalVariable)) {
        return false;
      }
      ```

2023-01-18 14:48 UTC, KochTobi commented on projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/ExperimentalDesign.java
> +        .anyMatch(variableInDesign -> variableInDesign.name().equals(variableToCheck.name()));
As you implemented equals in the variable class.
```suggestion
    return this.experimentalVariables.stream()
        .anyMatch(variableInDesign -> variableInDesign.equals(variableToCheck));
```
This way you cannot run out of sync with variable equality definition

2023-01-18 14:48 UTC, KochTobi commented on projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/ExperimentalDesign.java
> +      Supplier<Result<ExperimentalVariable<ExperimentalValue>, Exception>> variableExists) {
`variableExists` is only one possibility why the operation could fail. Maybe this can be renamed?

2023-01-18 14:48 UTC, KochTobi commented on projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/ExperimentalVariable.java
> +  }
The `levels` method does not return `VariableLevel`s but `ExperimentalValue`s. this might be confusing

2023-01-19 15:00 UTC, KochTobi submitted a review, later dismissed
Some minor concerns. Nothing blocking the approval tbh.
Good to have some experimental design logic in the code base.

2023-01-23 08:31 UTC, sven1103 commented on projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/VariableLevel.java
> +/**
🦅 added :)

2023-01-23 08:37 UTC, KochTobi approved these changes

2023-01-23 08:46 UTC, merged