Show error page or user notification in case of exceptions
qbicsoftware/data-manager-app pull request #227
Opened 2023-05-04 08:28 UTC by KochTobi

2023-05-04 08:30 UTC, KochTobi commented
includes changes from #191

2023-05-05 07:15 UTC, sven1103 commented on commons/src/main/java/life/qbic/application/commons/ApplicationException.java
> +  public static ApplicationException wrapping(Throwable e) {
Some documentation on the API to make the intention clear :)

2023-05-05 07:15 UTC, sven1103 commented on commons/src/main/java/life/qbic/application/commons/ApplicationException.java
> +  public static ApplicationException wrapping(String message, Throwable e) {
Documentation missing

2023-05-05 07:16 UTC, sven1103 commented on commons/src/main/java/life/qbic/application/commons/ApplicationException.java
> +  public static <E extends ApplicationException> ApplicationException wrapping(String message,
Missing docs

2023-05-05 07:17 UTC, sven1103 commented on vaadinfrontend/src/main/java/life/qbic/datamanager/exceptionhandling/ErrorMessageTranslationService.java
> +@Service
Docs missing :)

2023-05-05 07:17 UTC, sven1103 commented on vaadinfrontend/src/main/java/life/qbic/datamanager/exceptionhandling/UiExceptionHandler.java
> +public class UiExceptionHandler {
Java Docs missing

2023-05-05 07:18 UTC, sven1103 commented on vaadinfrontend/src/main/java/life/qbic/datamanager/exceptionhandling/routing/exception/ExceptionErrorPage.java
> +public class ExceptionErrorPage extends VerticalLayout implements ErrorPage<Exception> {
Java docs

2023-05-05 07:19 UTC, sven1103 requested changes
Only documentation on classes and API missing, the implementation looks good !

2023-05-05 11:35 UTC, sven1103 approved these changes
LGTM 🚀

2023-05-05 11:47 UTC, merged