Elevate navigation buttons and change mouseover cursor to pointer for all buttons
qbicsoftware/data-manager-app pull request #290
Opened 2023-07-04 13:27 UTC by Steffengreiner

**What was changed** 
Improve navigation bar [affordance](https://uxplanet.org/ux-design-glossary-how-to-use-affordances-in-user-interfaces-393c8e9686e4) through: 

1.) Elevation for navigation buttons
2.) Cursor change on mouseover for all buttons to pointer

**Before:**
![Bildschirmfoto 2023-07-04 um 15 22 47](https://github.com/qbicsoftware/data-manager-app/assets/29627977/7d5ff95c-63d2-48a0-83ef-49d9b9d3400f)

**After**
![Bildschirmfoto 2023-07-04 um 15 22 32](https://github.com/qbicsoftware/data-manager-app/assets/29627977/aa52032a-aa64-46f1-972c-f08395b0d94b)

2023-07-04 13:32 UTC, sven1103 requested changes
Please address the code smell. 

Introduce a constant, or collect the buttons in a list and iterate over them, assigning them the class name "elevated"

2023-07-04 16:01 UTC, Steffengreiner commented
@sven1103 I addressed the code smell by rewriting the component using our css styles which simplifies it greatly 🥳

2023-07-04 16:23 UTC, wow-such-code approved these changes
looks good to me, nice abstraction

2023-07-05 07:21 UTC, sven1103 approved these changes

2023-07-05 07:25 UTC, merged