Consume confirmation link and activate user
qbicsoftware/data-manager-app pull request #30
Opened 2022-05-31 12:46 UTC by sven1103

2022-05-31 13:00 UTC, KochTobi requested changes
Nice work. I left some comments mainly NITs. However, I would argue that we need to think about the `onSuccess` and `onFailure` methods.
Furthermore, there are some code smells (detected by sonarcloud). Maybe you could have a look into that and resolve them.

2022-05-31 13:02 UTC, sven1103 commented on webapp/src/main/java/life/qbic/AppConfig.java
> +  public EmailAddressConfirmation confirmEmailInput(UserRegistrationService userRegistrationService) {
In this case, I need the original use case class, so that i can set the use case output in the application class

2022-05-31 13:03 UTC, sven1103 commented on webapp/src/main/java/life/qbic/views/landing/LandingPageLayout.java
> +  }
hups, well spotted, a testing left-over

2022-05-31 13:06 UTC, sven1103 commented on webapp/src/main/java/life/qbic/views/login/LoginHandler.java
> +  }
true

2022-05-31 13:12 UTC, KochTobi commented
Hi @sven1103 
Thanks for addressing my comments. I would kindly ask you to reduce the code duplication and the number of code smells introduced here. After that we are good to go 😄

2022-05-31 14:41 UTC, KochTobi requested changes
Hi @sven1103 
Thank you for addressing the code smells. There are two left, that I would require for an approval.
[unused variable](https://sonarcloud.io/project/issues?pullRequest=30&issues=AYEaKVGW3dDsTp_XuRmr&open=AYEaKVGW3dDsTp_XuRmr&id=qbicsoftware_data-manager-app)
[accessor order](https://sonarcloud.io/project/issues?pullRequest=30&issues=AYEacwFTtqLetYjuPdPB&open=AYEacwFTtqLetYjuPdPB&id=qbicsoftware_data-manager-app)

2022-06-01 06:19 UTC, sven1103 commented
@KochTobi thanks for your review

2022-06-01 06:22 UTC, merged