Feature/dm 361 summary report user creation failure
qbicsoftware/data-manager-app pull request #34
Opened 2022-06-03 13:24 UTC by sven1103

2022-06-07 12:09 UTC, KochTobi requested changes
I am confused. Seems this PR goes to the wrong branch

2022-06-07 12:09 UTC, KochTobi commented on domain/src/main/java/life/qbic/apps/datamanager/services/UserRegistrationException.java
> +
Instead of wrapping the optional in the constructor, please move the wrapping to the getters.

2022-06-07 12:09 UTC, KochTobi commented on domain/src/main/java/life/qbic/apps/datamanager/services/UserRegistrationService.java
> +        var notificationId = notificationService.newNotificationId();
This will cause a massive merge conflict when the feature branch for email confirmation will be merged.

2022-06-07 12:09 UTC, KochTobi commented on domain/src/main/java/life/qbic/domain/user/Email.java
> +public class Email {
Why not `EmailAddress` directly? The user does not have an email attached to it but an email address.

2022-06-07 12:16 UTC, KochTobi requested changes

2022-06-07 12:16 UTC, KochTobi commented on domain/src/main/java/life/qbic/domain/usermanagement/policies/PasswordPolicy.java
> +      return new PolicyCheckReport(PolicyStatus.FAILED, "EncryptedPassword shorter than 8 characters.");
```suggestion
      return new PolicyCheckReport(PolicyStatus.FAILED, "Password shorter than 8 characters.");
```

2022-06-07 12:16 UTC, KochTobi commented on domain/src/test/groovy/life/qbic/domain/user/EmailSpec.groovy
> +}
we need to test for the correct behaviour as well. `expect valid email address creation works`

2022-06-07 12:16 UTC, KochTobi commented on domain/src/test/groovy/life/qbic/domain/user/FullNameSpec.groovy
> +    }
This test does not test for empty strings.

2022-06-07 12:16 UTC, KochTobi commented on domain/src/test/groovy/life/qbic/domain/usermanagement/policies/PasswordPolicySpec.groovy
> +        report.reason().equalsIgnoreCase("EncryptedPassword shorter than 8 characters.")
```suggestion
        report.reason().equalsIgnoreCase("Password shorter than 8 characters.")
```

2022-06-07 12:16 UTC, KochTobi commented on webapp/src/main/java/life/qbic/views/login/LoginHandler.java
> +    registeredLoginView.password.setErrorMessage("Invalid EncryptedPassword");
```suggestion
    registeredLoginView.password.setErrorMessage("Invalid Password");
```

2022-06-07 12:16 UTC, KochTobi commented on webapp/src/main/java/life/qbic/views/login/LoginLayout.java
> +    password = new PasswordField("EncryptedPassword");
```suggestion
    password = new PasswordField("Password");
```

2022-06-07 12:16 UTC, KochTobi commented on webapp/src/main/java/life/qbic/views/login/LoginLayout.java
> +    forgotPasswordButton = new Button("Forgot EncryptedPassword");
```suggestion
    forgotPasswordButton = new Button("Forgot Password");
```

2022-06-07 12:16 UTC, KochTobi commented on webapp/src/main/java/life/qbic/views/register/UserRegistrationHandler.java
> +    userRegistrationLayout.password.setErrorMessage("EncryptedPassword too short");
```suggestion
    userRegistrationLayout.password.setErrorMessage("Password too short");
```

2022-06-07 12:16 UTC, KochTobi commented on webapp/src/main/java/life/qbic/views/register/UserRegistrationHandler.java
> +    if (reason.equalsIgnoreCase("EncryptedPassword shorter than 8 characters.")) {
```suggestion
    if (reason.equalsIgnoreCase("Password shorter than 8 characters.")) {
```

2022-06-07 12:16 UTC, KochTobi commented on webapp/src/main/java/life/qbic/views/register/UserRegistrationLayout.java
> +        new ErrorMessage("EncryptedPassword too short", "Your password must be at least 8 characters long.");
```suggestion
        new ErrorMessage("Password too short", "Your password must be at least 8 characters long.");
```

2022-06-07 12:16 UTC, KochTobi commented on webapp/src/main/java/life/qbic/views/register/UserRegistrationLayout.java
> +    password = new PasswordField("EncryptedPassword");
```suggestion
    password = new PasswordField("Password");
```

2022-06-10 10:01 UTC, Steffengreiner commented
Heya @sven1103 and @KochTobi as discussed i cherry-picked the relevant commits from this PR to #35 to avoid branching confusion. Therefore I'd close this PR

2022-06-10 10:01 UTC, closed without merging