work in progress: send message to contacts on sample registration
qbicsoftware/data-manager-app pull request #384
Opened 2023-09-21 15:23 UTC by wow-such-code

* adds predefined email message that explains sample registration happened
* creates file from sample batch metadata to attach to message
* adds possibility to send attachments with emails
* sends email to principal investigator and project manager (and contact person if exists) upon successful sample registration

Open questions:
* Message class is in **authorization** package. what would be the best way to use it elsewhere? or should we predefine messages in another package?
* this will send emails with metadata to any email address that is added for the project. should there be some button to enable/disable this for testing purposes? what are the security implications to use this in production?

2023-10-09 14:52 UTC, sven1103 requested changes
Thank you @wow-such-code for your contribution.

I have some concernts, but I think they are easily resolvable. Let me know if sth is unclear.

2023-10-09 14:52 UTC, sven1103 commented on domain-concept/src/main/java/life/qbic/domain/concepts/communication/CommunicationService.java
> +  void send(Subject subject, Recipient recipient, Content content, String attachmentContent,
I suggest to introduce a record 'attachment' to keep the parameter list short.

2023-10-09 14:52 UTC, sven1103 commented on projectmanagement-domain/src/main/java/life/qbic/projectmanagement/application/authorization/acl/ProjectAccessService.java
> +  List<String> listActiveUsers(ProjectId projectId);
nice :+1:

2023-10-09 14:52 UTC, sven1103 commented on projectmanagement-domain/src/main/java/life/qbic/projectmanagement/application/policy/directive/InformUsersAboutBatchRegistration.java
> +    List<RecipientDTO> recipientsWithAccess = getUsersWithAccess(project.getId());
ah sorry, my mistake. The method promises to return users, not recipients. So you might need a static wrapper method like ``userToRecipient(UserInfo user)``

2023-10-09 14:52 UTC, sven1103 commented on projectmanagement-domain/src/main/java/life/qbic/projectmanagement/application/policy/directive/InformUsersAboutBatchRegistration.java
> +        attachmentContent, "sample_sheet.tsv");
that is QBiC legacy terminology, I suggest sth like ``batch-<name>-samples``

2023-10-09 14:52 UTC, sven1103 commented on projectmanagement-domain/src/main/java/life/qbic/projectmanagement/domain/project/sample/event/SampleBatchRegistered.java
> +/**
We already have a BatchRegistered Domain Event that must be reused here

2023-10-10 12:06 UTC, sven1103 commented on domain-concept/src/main/java/life/qbic/domain/concepts/communication/CommunicationService.java
> +  void send(Subject subject, Recipient recipient, Content content, Attachment attachment) throws CommunicationException;
Maybe some JDs :D

2023-10-10 12:09 UTC, sven1103 commented on projectmanagement-domain/src/main/java/life/qbic/projectmanagement/domain/project/service/BatchDomainService.java
> +  private void dispatchSuccessfulSampleBatchRegistration(String name, BatchId id, Project project) {
NIT:

```suggestion
  private void dispatchRegistration(String name, BatchId id, Project project) {
```

2023-10-10 12:13 UTC, sven1103 requested changes
One last request: domain events should be slim with simple data types to ensure serialization and not passing too much information around.

Instead of the project aggregate, you can pass the project id.

Second: why is the project id needed?

2023-10-13 15:27 UTC, Steffengreiner approved these changes
Nice Spot with the distinct users! LGTM 🚀

2023-10-13 15:35 UTC, merged