sort samples in batch-edit by sample code
qbicsoftware/data-manager-app pull request #475
Opened 2024-01-30 16:11 UTC by wow-such-code

2024-02-02 10:17 UTC, Steffengreiner submitted a review, later dismissed
Perfect 👌

2024-02-02 10:18 UTC, Steffengreiner requested changes
Although the code is perfect, I'd request to change the target branch to dev 😅

2024-02-02 11:03 UTC, KochTobi commented on user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/SampleInformationMain.java
> +        .map(sample -> convertSampleToSampleInfo(sample, experimentalGroups)).toList());
```suggestion
    List<SampleBatchInformationSpreadsheet.SampleInfo> sampleInfos = samples.stream()
        .map(sample -> convertSampleToSampleInfo(sample, experimentalGroups))
        .collect(Collectors.toCollection(ArrayList::new));
```

2024-02-02 11:04 UTC, KochTobi commented on user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/SampleInformationMain.java
> +        .map(sample -> convertSampleToSampleInfo(sample, experimentalGroups)).toList());
du kannst auch den stream schon sorten
```suggestion
    var sampleInfos = samples.stream()
        .map(sample -> convertSampleToSampleInfo(sample, experimentalGroups))
        .sorted(Comparator.comparing(o -> o.getSampleCode().code())
        .collect(Collectors.toCollection(ArrayList::new));
```

2024-02-05 10:08 UTC, Steffengreiner approved these changes
Send it! ✉️

2024-02-05 10:09 UTC, merged