Enable sample pool groups in proteomics measurements
qbicsoftware/data-manager-app pull request #511
Opened 2024-03-06 16:22 UTC by sven1103

2024-03-08 10:19 UTC, KochTobi requested changes
Some minor things and some things where the reasoning is missing.

2024-03-08 10:19 UTC, KochTobi commented on user-interface/src/main/java/life/qbic/datamanager/views/projects/project/measurements/MeasurementDetailsComponent.java
> +    proteomicsMeasurementGrid.addComponentColumn(
oh I did not know about the ComponentColumn

2024-03-08 10:19 UTC, KochTobi commented on user-interface/src/main/java/life/qbic/datamanager/views/projects/project/measurements/MeasurementMetadataUploadDialog.java
> +  private static Result<ProteomicsMeasurementMetadata, String> generatePxPRequest(
please adapt the method name. There is no request anymore

2024-03-08 11:25 UTC, sven1103 commented on project-management/src/main/java/life/qbic/projectmanagement/application/measurement/MeasurementMetadata.java
> +  }
These are properties that all Measurement Metadata will share

2024-03-08 14:33 UTC, sven1103 commented on project-management/src/main/java/life/qbic/projectmanagement/domain/model/measurement/MeasurementCode.java
> +  static class MeasurementCodeConverter implements AttributeConverter<MeasurementCode, String> {
what does it do?

2024-03-08 14:34 UTC, sven1103 commented on project-management/src/main/java/life/qbic/projectmanagement/domain/model/measurement/NGSMeasurement.java
> +  @Convert(converter = MeasurementCode.MeasurementCodeConverter.class)
I argue that my explicit notation is easier to navigate to the assigned converter

2024-03-08 14:37 UTC, sven1103 commented on project-management/src/main/java/life/qbic/projectmanagement/domain/model/measurement/ProteomicsMeasurement.java
> +    return Optional.ofNullable(comment.isBlank() ? null : comment);
Optional of null value returns Optional.empty. It is just a concise expression

2024-03-08 14:38 UTC, sven1103 commented on project-management/src/main/java/life/qbic/projectmanagement/domain/model/measurement/ProteomicsMeasurement.java
> +    }
null if is an Object that is not assigned, else for String values

2024-03-08 14:58 UTC, KochTobi commented on project-management/src/main/java/life/qbic/projectmanagement/domain/model/measurement/MeasurementCode.java
> +  static class MeasurementCodeConverter implements AttributeConverter<MeasurementCode, String> {
the same as `@Converter(...)` on the fields in JPA classes. But it is discovered automatically and used as a default for fields of type `MeasurementCode`

2024-03-08 14:59 UTC, KochTobi commented on project-management/src/main/java/life/qbic/projectmanagement/domain/model/measurement/NGSMeasurement.java
> +  @Convert(converter = MeasurementCode.MeasurementCodeConverter.class)
But you need to make sure you add it everywhere. I'd argue that finding implementations of interfaces is no difficult task nowadays.

2024-03-11 07:14 UTC, sven1103 commented on project-management/src/main/java/life/qbic/projectmanagement/domain/model/measurement/NGSMeasurement.java
> +  @Convert(converter = MeasurementCode.MeasurementCodeConverter.class)
Why everywhere? This is the only class that represents the JPA entity

2024-03-11 13:10 UTC, KochTobi approved these changes
LGTM

2024-03-11 13:10 UTC, merged