Introduces local domain event dispatcher
qbicsoftware/data-manager-app pull request #570
Opened 2024-05-17 11:51 UTC by sven1103

2024-05-17 13:00 UTC, wow-such-code requested changes
Thank you for the contribution, all of this makes sense. But it would be very useful to provide an example of how the original local event in the aggregate is created in the update use case.

2024-05-21 07:18 UTC, sven1103 commented
Hi @wow-such-code , but there is an example implemented already, for the Measurement Update in the PXP case :/

2024-05-21 08:21 UTC, wow-such-code submitted a review, later dismissed

2024-05-21 08:45 UTC, wow-such-code approved these changes

2024-05-21 08:52 UTC, merged