Refactor SamplePage UI to current Prototype
qbicsoftware/data-manager-app pull request #702
Opened 2024-07-09 15:42 UTC by Steffengreiner

**What was changed**

1.) search and download logic is now handled by the SampleMain component similiar to measurementmain to adhere to prototype page structure
2.) Disclaimers are shown if no samples and experimental groups are provided, and the sample and batch components are hidden accordingly. 
3.) User can now filter sampleGrid by values set in organismId
4.) Column widths for both grids are updated if information changes to ensure that the content is always readable. 
5.) User can move column order in samplegrid according to preferences
6.) User can resize columns 
7.) Sample Id column is frozen and batch action column is frozen so it's always usable
8.) Sample label column name was changed to sample name

2024-07-10 15:06 UTC, Shraddha0903 commented
Hey @Steffengreiner, awesomeee work! 😍 
Everything checks off. Just that it would be even better if the column rearranging and resizing settings are saved for the user.
But I had fun rearranging 😉  We can also extend the grid functionalities to the measurements and RAW data view.

2024-07-10 15:21 UTC, Shraddha0903 reviewed
Hey @Steffengreiner, awesomeee work! 😍
Everything checks off. Just that it would be even better if the column rearranging and resizing settings are saved for the user.
But I had fun rearranging 😉 We can also extend the grid functionalities to the measurements and RAW data view.

2024-07-12 15:53 UTC, wow-such-code requested changes
Looks beautiful, nice work!
One thing I noticed, however, is that the Filter field does not reset when changing projects (and at the same time the filter is then not applied to the table).

2024-07-18 09:46 UTC, wow-such-code approved these changes

2024-07-18 12:08 UTC, merged