Show orcId if present for users in their profile or show Anchor to link orcId
qbicsoftware/data-manager-app pull request #833
Opened 2024-09-12 15:06 UTC by Steffengreiner

**What was changed**

Provides the UI to show the Orcid Linkage if a user has an orcid account: 

![Screenshot 2024-09-12 at 17 01 40](https://github.com/user-attachments/assets/87417c91-b201-4ae9-aa82-784bf41d7011)

Alternatively provide a non-functional anchor for users without orcid account:
![Screenshot 2024-09-12 at 17 02 41](https://github.com/user-attachments/assets/b54fc144-d2ed-4739-a9da-5359c403040c)

Linkage will be handled in a seperate PR (see #740)

2024-09-25 09:47 UTC, wow-such-code approved these changes

2024-10-15 13:37 UTC, KochTobi requested changes
I am sorry but I think we cannot add it as is. As we do not have the functionality to `Link ORCID Account` we should not show this part. If you adapt this PR to only show linked ORCID accounts rather and not link new ones, I remove the change request again.

2024-11-14 09:25 UTC, sven1103 commented
I think we can still render the linkage, if it is present. If the PR introduces the non-functional link, then I would ask to remove it and introduce it with the feature that supports it.

2024-11-14 13:19 UTC, KochTobi approved these changes

2024-11-14 13:20 UTC, merged