Add support for confounding variables
qbicsoftware/data-manager-app pull request #877
Opened 2024-10-30 09:17 UTC by KochTobi

Addresses #642

2024-10-30 09:18 UTC, KochTobi commented
As confounding variables are valid for all samples in an experiment (including samples where a value might not yet been known), I decided to go for including empty variables in the samples.

2025-01-22 15:04 UTC, KochTobi commented
For this to work, [sql/complete-schema.sql](https://github.com/qbicsoftware/data-manager-app/blob/5b0befc6f99b394c0dd848de4afe01382d684e80/sql/complete-schema.sql) has to be executed on the database

2025-01-27 07:36 UTC, sven1103 commented
@KochTobi there are some conflicts with the target branch `development`

2025-01-27 07:39 UTC, sven1103 commented
@KochTobi can you elaborate more on the changes in the database? I also encourage to look into database versioning solutions like Flyway. I have some concerns with our current database schema development strategy: hoping for the best and no way back.

2025-01-27 07:59 UTC, sven1103 requested changes
Some minor change requests, but I have some concerns with how we deal with database changes.

2025-01-27 07:59 UTC, sven1103 commented on project-management/src/main/java/life/qbic/projectmanagement/application/sample/SampleMetadata.java
> +  public static SampleMetadata fromNewToExisting(SampleId id, SampleMetadata sampleMetadata) {
I am unsure about the naming here: the method just creates a new sample metadata record with the given sample ID. 
I suggest a naming that describes what it does, instead of assuming context. 

`addSampleID(SampleId id, SampleMetadata metadata)`

2025-01-27 07:59 UTC, sven1103 commented on project-management/src/main/java/life/qbic/projectmanagement/application/sample/SampleRegistrationServiceV2.java
> +        ExperimentId.parse(experiment.id()));
I think we overdid it here big time with the Identifier... Imo there is no need to parse, because it does not have any semantics or schema. It is just a string value generated from the UUID generator. You either find an object with the ID in the database, or you dont. 
Happy to see some simplification.

2025-01-27 07:59 UTC, sven1103 commented on project-management/src/main/java/life/qbic/projectmanagement/application/sample/SampleRegistrationServiceV2.java
> +  @Transactional(propagation = Propagation.REQUIRES_NEW)
What does this annotation do? Why is it needed?

2025-01-27 07:59 UTC, sven1103 commented on project-management/src/main/java/life/qbic/projectmanagement/application/sample/SampleRegistrationServiceV2.java
> +        registeredSample.getValue().confoundingVariables().forEach((k, v) -> levels.put(k.id(), v));
suggestion: you can use `Collectors.toMap()` here, makes it more concise.

2025-01-27 07:59 UTC, sven1103 commented on project-management/src/main/java/life/qbic/projectmanagement/application/sample/SampleRegistrationServiceV2.java
> +      updatedSample.getValue().confoundingVariables().forEach((k, v) -> levels.put(k.id(), v));
Again ``Collectors.toMap()``

2025-01-27 08:45 UTC, KochTobi commented
> @KochTobi there are some conflicts with the target branch `development`

Yes I resolved it.

2025-01-27 08:49 UTC, KochTobi commented
> @KochTobi can you elaborate more on the changes in the database? I also encourage to look into database versioning solutions like Flyway. I have some concerns with our current database schema development strategy: hoping for the best and no way back.

Hi Sven. I simply merged all the sql files to set up the database into one and added the tables for confounding variables. In this case the database schema is simply extended by the tables of confounding variables (samples, experiment and so forth are not touched).
I will happily look into Flyway or other database migration solutions. In the case of this PR I only recorded the current database scheme we have (plus the tables I added).

Even thou the topic of database migration and future proofing is of great importance, I would like to separate the investigation on database migration and future proofing from this PR.

2025-01-27 08:51 UTC, KochTobi commented on project-management/src/main/java/life/qbic/projectmanagement/application/sample/SampleRegistrationServiceV2.java
> +        ExperimentId.parse(experiment.id()));
I agree!

2025-01-27 08:55 UTC, KochTobi commented on project-management/src/main/java/life/qbic/projectmanagement/application/sample/SampleRegistrationServiceV2.java
> +  @Transactional(propagation = Propagation.REQUIRES_NEW)
The transactional annotation is needed to indicate a transaction taking place. It starts a transaction in the database and commits changes when exiting the method. The propagation property tells spring that a new transaction is to be created for this operation. The default behaviour is that an existing active transaction is used and if there is none that one is created. I do not think we need to explicity create a new transaction here so I removed the propagation type.

2025-01-27 09:05 UTC, KochTobi commented on project-management/src/main/java/life/qbic/projectmanagement/application/sample/SampleRegistrationServiceV2.java
> +        registeredSample.getValue().confoundingVariables().forEach((k, v) -> levels.put(k.id(), v));
To use `Collectors#toMap`, I need to create a stream first. So it does not make it more readable I feel. However I have no strong opinion on the matter. So if you think the lower example is better I will change it.
```
confoundingVariables().foreach((k, v) -> levels.put(k.id(), v));
```
```
registeredSample.getValue().confoundingVariables()
            .entrySet()
            .stream()
            .collect(Collectors.toMap(
                entry -> entry.getKey().id(),
                Entry::getValue));
```

2025-01-27 09:05 UTC, KochTobi commented on project-management/src/main/java/life/qbic/projectmanagement/application/sample/SampleRegistrationServiceV2.java
> +      updatedSample.getValue().confoundingVariables().forEach((k, v) -> levels.put(k.id(), v));
see https://github.com/qbicsoftware/data-manager-app/pull/877#discussion_r1930180547

2025-01-27 13:04 UTC, sven1103 commented on project-management/src/main/java/life/qbic/projectmanagement/application/sample/SampleRegistrationServiceV2.java
> +        registeredSample.getValue().confoundingVariables().forEach((k, v) -> levels.put(k.id(), v));
Yes, just nit, but to be fair it is:

```java
Map<VariableReference, String> levels = new HashMap<>();
registeredSample.getValue().confoundingVariables().forEach((k, v) -> levels.put(k.id(), v));
```

vs 

```java
var levels = registeredSample.getValue().confoundingVariables()
                                .entrySet().stream()
                                .collect(Collectors.toMap(entry -> entry.getKey().id(), Entry::getValue));

The last one is side-effect free, vs the first is depending on an external map initialization :P

2025-01-28 10:54 UTC, sven1103 approved these changes
Great work @KochTobi, i am looking forward to the users feedback!

2025-01-28 10:55 UTC, KochTobi commented on project-management/src/main/java/life/qbic/projectmanagement/application/sample/SampleRegistrationServiceV2.java
> +  @Transactional(propagation = Propagation.REQUIRES_NEW)
There are different scenarios:

1. no `@Transactional` annotation
2. a `@Transactional` annotation without `Propagation.REQUIRES_NEW`
3. a `@Transactional` annotation the default propagation

in 1. there will be an exception if the method is called from outside a transactional context. In our case no transactional context exists so the exception will be thrown. Without any transaction, no rollback is possible

in 2. at the start of the method a new transaction will be created, suspending an existing transaction if any already exists in this scope. The changes are made within the new transaction which is committed when the method exits (or rolled back in case of exceptions). After the newly created transaction finishes (commit or rollback) the previously suspended transaction continues. 

in 3. when called from a transactional scope (already existing transaction) the operations within the method are appended/added to the existing transaction. If the method throws an exception the complete transaction (including the changes made before this method was called) are rolled back. If no transaction existed when the method is called, a new transaction is created.

The difference between 2. and 3. is that in 2. a transaction is suspended. Rollbacks do not affect a scope outside of the method in 2. Suspending transactions bears a risk of deadlocking the system. If the amount of maximal transactions is limited and the creation of the transaction fails, there might be a scenario where the original transaction is kept in a suspended state further limiting the amount of available transactions. 
We also want to rollback an existing transaction in case of exceptions so only rolling back changes made in this method is not what we want I think.
Thus the propagation type of `REQUIRES_NEW` was wrong here.

2025-01-28 11:04 UTC, KochTobi commented
> > @KochTobi can you elaborate more on the changes in the database? I also encourage to look into database versioning solutions like Flyway. I have some concerns with our current database schema development strategy: hoping for the best and no way back.
> 
> Hi Sven. I simply merged all the sql files to set up the database into one and added the tables for confounding variables. In this case the database schema is simply extended by the tables of confounding variables (samples, experiment and so forth are not touched). I will happily look into Flyway or other database migration solutions. In the case of this PR I only recorded the current database scheme we have (plus the tables I added).
> 
> Even thou the topic of database migration and future proofing is of great importance, I would like to separate the investigation on database migration and future proofing from this PR.

https://github.com/qbicsoftware/data-manager-app/issues/1000 <- to track the need

2025-01-28 11:05 UTC, merged