Show comments for NGS and ProteomicsMeasurements
qbicsoftware/data-manager-app pull request #962
Opened 2024-12-20 13:43 UTC by Steffengreiner

**What was changed**
Currently the Proteomics and Ngs Measurements don't show the provided comments during measurement registration. This error appears for pooled and unpooled measurements. 

This PR aims to provide the comments for singular Samples within the measurement overview, while providing the possiblity to open the information dialog for pooled samples

2025-01-08 09:24 UTC, sven1103 commented
@Steffengreiner what is the related issue? Please always link the corresponding issue in the PR via GitHub's x-ref feature:
![image](https://github.com/user-attachments/assets/ef4832f9-22b7-48da-a729-fa8dcd5c8014)

2025-01-08 09:24 UTC, sven1103 requested changes
Missing x-ref to an issue.

2025-01-08 10:02 UTC, Steffengreiner commented
Heya @sven1103, Thanks for the Feedback. I linked the issue in question 👍

2025-01-13 14:09 UTC, sven1103 commented on user-interface/src/main/java/life/qbic/datamanager/views/projects/project/measurements/MeasurementDetailsComponent.java
> +          if (!measurement.isPooledSampleMeasurement()) {
Negations are harder to read and understand, especially that "!" is not part our natural language. I suggest to include a method like `isSingleSampleMeasurement()` to reflect the positive case you are looking for.

2025-01-13 14:14 UTC, sven1103 commented on user-interface/src/main/java/life/qbic/datamanager/views/projects/project/measurements/MeasurementDetailsComponent.java
> +                measurement.specificMeasurementMetadata().stream().findFirst().orElseThrow().comment()
I am not sure what happens here. I also think, that we should handle the `orElseThrow()` with care, since it will cause exceptions that are not of importance.

2025-01-13 14:19 UTC, sven1103 requested changes
thank you @Steffengreiner !

Some minor requests, questions before it is ready to merge

2025-01-14 14:58 UTC, sven1103 approved these changes
Nicely done @Steffengreiner !

2025-01-14 14:59 UTC, merged